-- Backfill Suisse : leads de l'export « Target OS - Prospects » (avant leads FR n8n)
-- Supabase → SQL Editor → Run
-- N'écrase pas les leads déjà marqués FR.

UPDATE public.prospects
SET pays = 'CH'
WHERE pays IS DISTINCT FROM 'FR'
  AND entreprise IN (
    'Beirut Bistrot',
    'le Méridien',
    'Cico Coffee & Food',
    'Patate Gourmande',
    'Le vieux martin',
    'Remor',
    'Boulangerie - Pâtisserie -Restaurant Bessa',
    'Restaurant La Grotta',
    'boulangerie patisserie Bessa Geneve',
    'Tea room de l''Athénée',
    'Istanbul',
    'Back Office',
    'Restaurant Dragon',
    'Espresso Club',
    'il Forno a Legna',
    'Le Lyrique',
    'Thai Phuket',
    'Aimé Pouly - Helvétique',
    'La Boursière',
    'Le Dorian',
    'Manora',
    'Colosseo',
    'Restaurant de la Plage SA',
    'F.P.Journe Le Restaurant',
    'Les Armures Hôtel-Restaurant',
    'Bischero',
    'Floatinn',
    'Restaurant Kozan',
    'LE PERRON',
    'Pâtisserie Ducret SA',
    'Prestige Gourmand',
    'Musée d''art et d''histoire',
    'Olé-Olé Restaurant',
    'Restaurant Bombay',
    'Carosello',
    'Le Colibri',
    'Na Village',
    'Restaurant Pasta People',
    'Café du Centre',
    'Pied de Cochon',
    'Bar Nobel',
    'De La Paix',
    'Restaurant Jaï',
    'Baï-Toey',
    'Café Coutume',
    'Frédéric Ducret',
    'Jardin du Bonheur',
    'Kozan',
    'Kuk',
    'Les Tilleuls',
    'Tibet Café',
    'Braseiro Restaurant, Cafe & Pizzeria',
    'Cafe-Restaurant Les Savoises',
    'Cave du boucher - Restaurant Grill',
    'Cave-Bar & Restaurant Le180',
    'Restaurant Vieux-Bois',
    'Erawan Take Away & Thai Restaurant',
    'Il Marinaio | Restaurant Italien',
    'Jacky Wei Restaurant',
    'Ketori Restaurant',
    'Le Restaurant des Joueurs',
    'Mare Restaurant',
    'McDonald''s Restaurant',
    'Miski restaurant - cevicheria',
    'Mövenpick Restaurant',
    'Restaurant Bistronomique Métropole',
    'Restaurant Capa Negra, Arifi',
    'Restaurant Cho Lon',
    'Restaurant Edelweiss',
    'Restaurant El Mektoub',
    'Restaurant Grand Chene',
    'Restaurant Indian Corner',
    'Restaurant Kung Fu 功夫',
    'Restaurant L''Attique',
    'Restaurant Le Chat Rouge',
    'Restaurant Le Lacustre',
    'Restaurant le Mekong',
    'Restaurant Le Petit Bordelais',
    'Restaurant MAITIGHAR | Genève| Nepali & indian restaurant menu',
    'Restaurant Namura',
    'Restaurant Naya',
    'Restaurant Pad Thai, Lumpleardthum',
    'Restaurant Syrien',
    'Restaurant Tosca',
    'Restaurant Traiteur Les Trois Phéniciens',
    'Restaurant ZHOU YU',
    'Shahi Restaurant',
    'Soghateh Gilan Restaurant',
    'Ukiyo Noodlebar & Restaurant',
    'Buvette Bains des Pâquis',
    'Balila',
    'David Bourdenet',
    'SACHI',
    'enFaim Sàrl',
    'la Bella Vita',
    '71 Bar Restaurant',
    'Broadway bar restaurant',
    'Café Restaurant de l''Hôtel-de-Ville',
    'Café-Restaurant de l''Union',
    'Coop Restaurant',
    'Cerutti Sanitaires SA',
    'Grosch SA',
    'AGALIA couverture peinture',
    'aeno Sàrl',
    'DEP SA Dépannage Sanitaire',
    'Hoegen, Pierre',
    'Musa Sanitaires Sàrl',
    'Benjamin FAHY Toiture Ferblanterie',
    'Burtin Alex',
    'Eco Rénove',
    'FerblanTech Solutions Sàrl',
    'H2O zero SARL',
    'Home-Clima',
    'MG Eau Sàrl',
    'Pool Sanit Sàrl',
    'RED Martin Sanitaires SA',
    'Sanimmo Nika SA',
    'Swiss-technics',
    'Ets Cottier',
    'Firex Sàrl',
    'HB Sanitaire Sàrl',
    'MH Sanitaires Sàrl',
    'SONATEC GENEVE-VAUD, Alain Zwahlen',
    'TIRONA SANITAIRE - titulaire Sherifi Ademi',
    'UM TECHNICS Sàrl',
    'Stragiotti, Gildo',
    'Maison Victoor Sàrl',
    'Thermibel',
    'Borga Toitures SA',
    'Ambiance sanitaire - Dépannage 7/7 24/24',
    'CVC Technique Sarl',
    'R3Sanitaires SA',
    'Constantin Georges SA',
    'M B Habitat Sàrl, succursale de Nyon',
    'MBHabitat Sàrl',
    'J.-P. Soguel Couverture et Ferblanterie SA',
    'JM Rebetez Sàrl'
  );

-- Secours : tout lead historique sans pays (hors FR) = Suisse
UPDATE public.prospects
SET pays = 'CH'
WHERE pays IS NULL;

SELECT pays, COUNT(*) AS total
FROM public.prospects
GROUP BY pays
ORDER BY pays;
